apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-config-data
  labels:
    app: dotstat
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: dotstat-hostpath
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3d-dotstat-server-0
  hostPath:
    path: /var/lib/dotstat/config-data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mssql
  labels:
    app: dotstat
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: dotstat-hostpath
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3d-dotstat-server-0
  hostPath:
    path: /var/lib/dotstat/mssql
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-keycloak-db
  labels:
    app: dotstat
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: dotstat-hostpath
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3d-dotstat-server-0
  hostPath:
    path: /var/lib/dotstat/keycloak-db
    type: DirectoryOrCreate
