apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongo
  namespace: dotstat
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: dotstat-hostpath
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-mongo
