apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-config-data
  namespace: dotstat
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: dotstat-hostpath
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-config-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mssql
  namespace: dotstat
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: dotstat-hostpath
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-mssql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-keycloak-db
  namespace: dotstat
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: dotstat-hostpath
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-keycloak-db
