apiVersion: v1
kind: Secret
metadata:
  name: dotstat-secrets
  namespace: dotstat
stringData:
  SQL_SERVER_PASSWORD: "P@ssw0rd!"
  COMMON_DATABASE_NAME: "dotstat-common"
  COMMON_DATABASE_USER: "common"
  COMMON_DATABASE_PASSWORD: "P@ssw0rd!"
  DATA_DATABASE_NAME: "dotstat-data"
  DATA_DATABASE_USER: "data"
  DATA_DATABASE_PASSWORD: "P@ssw0rd!"
  MAPPING_DATABASE_NAME: "dotstat-mapping"
  MAPPING_DATABASE_USER: "mapping"
  MAPPING_DATABASE_PASSWORD: "P@ssw0rd!"
  KEYCLOAK_DATABASE_NAME: "dotstat-keycloak"
  KEYCLOAK_DATABASE_USER: "keycloak"
  KEYCLOAK_DATABASE_PASSWORD: "P@ssw0rd!"
  KEYCLOAK_ADMIN_USER: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "P@ssw0rd!"
  KEYCLOAK_CLIENT_SECRET: "VgBhOwwEmvbgaQWRcwJYaiO75zP1PS5H"
  SEARCH_API_KEY: "apikey!"
  COMMON_CS: "Server=sqlserver;Database=dotstat-common;User=common;Password=P@ssw0rd!;TrustServerCertificate=True;"
  DATA_CS: "Server=sqlserver;Database=dotstat-data;User=data;Password=P@ssw0rd!;TrustServerCertificate=True;"
  MAPPING_CS: "Server=sqlserver;Database=dotstat-mapping;User=mapping;Password=P@ssw0rd!;TrustServerCertificate=True;"
  KEYCLOAK_JDBC_URL: "jdbc:postgresql://keycloak-database:5432/dotstat-keycloak"
  EXEC_PARAMS_COMMON: "upgrade --connectionString Server=sqlserver;Database=dotstat-common;User=sa;Password=P@ssw0rd!;TrustServerCertificate=True; --commonDb --loginName common --loginPwd P@ssw0rd! --force"
  EXEC_PARAMS_DATA: "upgrade --connectionString Server=sqlserver;Database=dotstat-data;User=sa;Password=P@ssw0rd!;TrustServerCertificate=True; --dataDb --loginName data --loginPwd P@ssw0rd! --force"
  EXEC_PARAMS_MAPPING: "upgrade --connectionString Server=sqlserver;Database=dotstat-mapping;User=sa;Password=P@ssw0rd!;TrustServerCertificate=True; --mappingStoreDb --loginName mapping --loginPwd P@ssw0rd! --force"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dotstat-config
  namespace: dotstat
data:
  CONFIG_DATA_PROVIDER: "fs"
  DATA_DIRECTORY: "/app/data"
  KEYCLOAK_REALM: "demo"
  KEYCLOAK_CLIENT_ID: "stat-suite"
  KEYCLOAK_AUTHORITY_URL: "http://keycloak:8080/realms/demo"
  KEYCLOAK_AUTH_URL: "http://keycloak:8080/realms/demo/protocol/openid-connect/auth"
  TRANSFER_PORT: "7004"
  MAILDEV_INCOMING_MAIL_PORT: "25"
  AUTH_SERVICE_PORT: "7006"
  DATA_LIFECYCLE_MANAGER_PORT: "7002"
  DATA_EXPLORER_PORT: "7003"
  NSI_PORT: "81"
  SFS_PORT: "7005"
  TENANT_ID: "demo"
